# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCxrjb03JfrsplSeNOp5JG_Tu4YtpCoc
"""

import pandas as pd

df=pd.read_csv('clean_yield_data.csv')

df.shape

df.head()

df.isnull().sum() # Check for Null values

"""There are no Null values in the given data"""

df.duplicated().sum() # Check for duplicates

"""There are no Duplicates"""